### ISSUE TITLE
希望框架提供浏览器上下文参数捕获，/command内部agent能对接dify或者gm的atom实现

### ISSUE THREAD

**Issue by abigail830** [yingrui/gluonmeson-chrome-extension#22]
希望框架提供浏览器上下文参数捕获，/command内部agent能对接dify或者gm的atom实现
这样更多人更低门槛能参与到插件编辑中

**Comment by yingrui** [comment]
Be able to add BA Copilot agent url in popup window, so the Guru Mason can send request to backend to GluonMeson to generate story

**Comment by yingrui** [comment]
The agent performance and problem in GluonMeson need to be investigated.
